# Generated by Django 4.2.14 on 2024-07-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_email',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.CharField(),
        ),
    ]
